
---
events:
  -
    kind: "message-v1"
    backtrace:
      - "/home/alex/.local/lib/python3.10/site-packages/cmake/data/share/cmake-3.29/Modules/CMakeDetermineSystem.cmake:205 (message)"
      - "CMakeLists.txt:3 (project)"
    message: |
      The system is: Linux - 5.15.0-105-generic - x86_64
...
