on: [push]

jobs:
  run_dockerfiles:
    runs-on: ubuntu-latest
    name: Check docker-container-builds
    steps:
        - uses: actions/checkout@master     
        - uses: satackey/action-docker-layer-caching@v0.0.11
          # Ignore the failure of a step and avoid terminating the job.
          continue-on-error: true
        - name: Build the Docker image
          run: docker build . --file dockerfile --tag gst-metartp-img
        - name: Run the Docker image with gst-inspect-1.0 metahandle
          run: docker run --rm gst-metartp-img gst-inspect-1.0 metahandle
        - name: Run the Docker image with meta2rtp
          run: docker run --rm gst-metartp-img gst-inspect-1.0 meta2rtp
        - name: Run the Docker image with sender pipeline
          run: docker run --rm gst-metartp-img gst-launch-1.0 -v videotestsrc num-buffers=100 is-live=true ! 'video/x-raw, width=(int)240, height=(int)240, framerate=(fraction)30/1' ! videoconvert ! metahandle modus=writer ! videoconvert  ! x264enc key-int-max=15 ! rtph264pay mtu=1300 ! meta2rtp modus=meta2rtp ! udpsink host=127.0.0.1 port=5555


